
POST http://localhost:3001/api/notes 
content-type: application/json

{
    "content":"Esto es una nueva nota",
    "important": true,
    "userId": "6240cfeacab6c68e1c12cbbb"
} 


###

POST http://localhost:3001/api/notes 
content-type: application/json

